# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
warnings_are_errors: true
sudo: false
cache: packages

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
      - libgit2-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

# Install the bleeding edge version of a package from github (eg to pick
# up a not-yet-released bugfix)
# r_github_packages:
